const BOARD_SIZE = 10;

const MESSAGE_TYPES = {
  REGISTER: 'REGISTER',
  LOGOUT: 'LOGOUT',
  INVITE: 'INVITE',
  ACCEPT_INVITE: 'ACCEPT_INVITE',
  CREATE_GAME: 'CREATE_GAME',
  JOIN_GAME: 'JOIN_GAME',
  LEAVE_GAME: 'LEAVE_GAME',
  SHIPS_PLACED: 'SHIPS_PLACED',
  ATTACK: 'ATTACK',
  ATTACK_RESULT: 'ATTACK_RESULT',
  CHAT: 'CHAT',
  GAME_OVER: 'GAME_OVER',
  ERROR: 'ERROR',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  SET_PLAYERS: 'SET_PLAYERS',
  RECONNECTED: 'RECONNECTED',
  GAME_CREATED: 'GAME_CREATED',
  GAME_JOINED: 'GAME_JOINED',
  GAME_LEFT: 'GAME_LEFT',
  GAME_READY: 'GAME_READY',
  START_GAME: 'START_GAME'
};

const GAME_PHASES = {
  PLACEMENT: 'placement',
  BATTLE: 'battle'
};

const BOARD_CELL_STATES = {
  EMPTY: null,
  HIT: 'hit',
  MISS: 'miss'  
};

const TIME_INTERVALS = {
  GAME_CLEANUP: 3600000, // 1 hour in milliseconds
  PLAYER_DISCONNECT: 60000, // 1 minute in milliseconds
  HEARTBEAT: 30000 // 30 seconds in milliseconds
};

module.exports = {
  BOARD_SIZE,
  MESSAGE_TYPES,
  GAME_PHASES,
  BOARD_CELL_STATES,
  TIME_INTERVALS
};